// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxF78c0FqdKalc83BQMn2KtXvSNYMXLVk',
    appId: '1:983025779544:web:b5c09aeb087bcc064f1b2d',
    messagingSenderId: '983025779544',
    projectId: 'digicrafters-9d396',
    authDomain: 'digicrafters-9d396.firebaseapp.com',
    storageBucket: 'digicrafters-9d396.appspot.com',
    measurementId: 'G-HB6RXHCYB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI8dePlxeNkDrEhACvKj56mpTj4jtRGhM',
    appId: '1:983025779544:android:0ff817a4949d915d4f1b2d',
    messagingSenderId: '983025779544',
    projectId: 'digicrafters-9d396',
    storageBucket: 'digicrafters-9d396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYdqNvUZ6OIb9M1a14E9xIi7Yo6rB0zIc',
    appId: '1:983025779544:ios:fcea551c45366fc04f1b2d',
    messagingSenderId: '983025779544',
    projectId: 'digicrafters-9d396',
    storageBucket: 'digicrafters-9d396.appspot.com',
    iosBundleId: 'com.example.finathonApp',
  );
}
